[project]
name = "yaxmldiff"
version = "0.2.0"
description = "yaxmldiff is Yet Another XML Differ"
dynamic = ["readme"]
requires-python = ">= 3.10"
authors = [
  {name = "Lukas Atkinson", email = "opensource@LukasAtkinson.de"}
]
license = {text = "Apache-2.0"}
keywords = ["xml", "diff"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Testing",
  "Topic :: Text Processing :: Markup :: XML",
]
dependencies = [
  "lxml>=5",  # not entirely sure what an appropriate constraint would be
]

[project.urls]
"GitHub"        = "https://github.com/latk/yaxmldiff.py"
"Issue Tracker" = "https://github.com/latk/yaxmldiff.py/issues"

[dependency-groups]
dev = [
    "mypy>=2.2.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.21",
    "types-lxml>=2026.2.16",
]

[build-system]
requires = ["hatchling>=1.11", "hatch-fancy-pypi-readme>=24.1.0"]
build-backend = "hatchling.build"

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"
fragments = [
  { path = "README.md" },
  { text = "\n\n" },
  { path = "CHANGELOG.md" },
]

[tool.mypy]
disallow_any_decorated = true
disallow_any_expr = true
disallow_any_generics = true
disallow_any_unimported = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
implicit_reexport = false
pretty = true
strict_equality = true
strict_equality_for_none = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true

[tool.pytest.ini_options]
addopts = "--doctest-glob=*.md"

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "W",  # pycodestyle warnings
  "F",  # pyflakes
  "I",  # isort
  "B",  # bugbear
  "C90",  # mccabe
  "N",  # naming
  "C4",  # comprehensions
  "PYI",  # types
  "RET",  # return statements
  "SIM",  # possible simplifications
  "PL",  # pylint
  "TRY",  # exception handling
  "RUF",
  "D", # docstyle
  "UP",  # upgrade
  "ANN",  # type annotations
  "S",  # bandit
]
ignore = [
  "E501",  # line length is decided by the formatter
  "S101",  # allow asserts
  "D203", "D213",  # docstring positioning rules
  "D401",  # allow descriptive (non-imperative) docstrings
  "TRY003",  # all inline exception messages
]

[tool.ruff.lint.per-file-ignores]
"tests/**.py" = [
  "D100",  # undocumented-public-module
]

[tool.coverage]
run.branch = true
report.show_missing = true
