target-version = "py37"  # TODO replace with project.requires-python

[lint]
select = [
  "E",  # pycodestyle errors
  "W",  # pycodestyle warnings
  "F",  # pyflakes
  "I",  # isort
  "B",  # bugbear
  "C90",  # mccabe
  "N",  # naming
  "C4",  # comprehensions
  "PYI",  # types
  "RET",  # return statements
  "SIM",  # possible simplifications
  "PL",  # pylint
  "TRY",  # exception handling
  "RUF",
  # "D", # docstyle  TODO enable
  # "UP",  # upgrade  TODO enable
  "ANN",  # type annotations  TODO enable
  "S",  # bandit TODO enable
]
ignore = [
  "E501",  # line length is decided by the formatter
  "S101",  # allow asserts
  "ANN101", "ANN102",  # don't require annotation on self
]