name: CI
on: [push, pull_request]

env:
  TASK_PYTHON: '3.12'

jobs:

  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.8', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv sync --all-extras --dev
      - run: uv run nox --non-interactive --session test

  lint:
    name: Lint and Typecheck
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.TASK_PYTHON }}
      - run: uv sync --all-extras --dev
      - run: uv run nox --non-interactive --session lint
      - run: uv run nox --non-interactive --session typecheck

  dist:
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.TASK_PYTHON }}
      - run: uv build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  release:
    needs: [dist, typecheck, lint]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - run: ls -l dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
